//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimeSumary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingTypeUser
    {
        public int Id { get; set; }
        public int IdSumaryPime { get; set; }
        public int IdBillingType { get; set; }
    
        public virtual BillingType BillingType { get; set; }
        public virtual SumaryPime SumaryPime { get; set; }
    }
}
