
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PimeSumary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BillingTypeUser
{

    public int Id { get; set; }

    public int IdSumaryPime { get; set; }

    public int IdBillingType { get; set; }

    public string Reference { get; set; }



    public virtual BillingType BillingType { get; set; }

    public virtual SumaryPime SumaryPime { get; set; }

}

}
