//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimeSumary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PimeSumaryEntities : DbContext
    {
        public PimeSumaryEntities()
            : base("name=PimeSumaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillingType> BillingType { get; set; }
        public virtual DbSet<BillingTypeUser> BillingTypeUser { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<SumaryPime> SumaryPime { get; set; }
    }
}
