

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PimeSumary.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class PimeSumaryEntities : DbContext
{
    public PimeSumaryEntities()
        : base("name=PimeSumaryEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<BillingType> BillingType { get; set; }

    public virtual DbSet<BillingTypeUser> BillingTypeUser { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<SumaryPime> SumaryPime { get; set; }

}

}

