
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PimeSumary.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public int Id { get; set; }

    public int IdSumaryPime { get; set; }

    public string NameProduct { get; set; }

    public Nullable<decimal> UnitPrice { get; set; }



    public virtual SumaryPime SumaryPime { get; set; }

}

}
